"""tools 工具系统测试"""

from agentorchestra.tools.base import AutoGeneratedTool, Tool, ToolParameter
from agentorchestra.tools.errors import ToolErrorCode
from agentorchestra.tools.registry import ToolRegistry
from agentorchestra.tools.response import ToolResponse, ToolStatus


class SimpleTool(Tool):
    def __init__(self):
        super().__init__(name="simple", description="简单工具", expandable=False)

    def get_parameters(self):
        return [ToolParameter(name="x", type="string", description="输入", required=True)]

    def run(self, parameters):
        return ToolResponse.success(text=f"got: {parameters.get('x')}")


class TestToolRegistry:
    def test_register_and_get_tool(self):
        registry = ToolRegistry()
        tool = SimpleTool()
        registry.register_tool(tool)
        assert registry.get_tool("simple") is tool
        assert "simple" in registry.list_tools()

    def test_register_function(self):
        registry = ToolRegistry()

        def my_func(x: str) -> str:
            """测试函数"""
            return f"processed: {x}"

        registry.register_function(my_func)
        func = registry.get_function("my_func")
        assert func is not None
        assert callable(func)

    def test_execute_tool_object(self):
        registry = ToolRegistry()
        registry.register_tool(SimpleTool())
        resp = registry.execute_tool("simple", '{"x": "hello"}')
        assert resp.status == ToolStatus.SUCCESS
        assert resp.text == "got: hello"

    def test_execute_tool_not_found(self):
        registry = ToolRegistry()
        resp = registry.execute_tool("nonexistent", "x")
        assert resp.status == ToolStatus.ERROR
        assert resp.error_info["code"] == ToolErrorCode.NOT_FOUND


class TestToolResponse:
    def test_success(self):
        resp = ToolResponse.success(text="ok", data={"k": 1})
        assert resp.status == ToolStatus.SUCCESS
        assert resp.data == {"k": 1}

    def test_error(self):
        resp = ToolResponse.error(code="NOT_FOUND", message="x")
        assert resp.status == ToolStatus.ERROR
        assert resp.error_info == {"code": "NOT_FOUND", "message": "x"}

    def test_to_dict(self):
        resp = ToolResponse.success(text="ok")
        data = resp.to_dict()
        assert data["status"] == "success"


class TestAutoGeneratedTool:
    def test_auto_generate_from_signature(self):
        def add(a: int, b: int) -> int:
            """两数相加"""
            return a + b

        tool = AutoGeneratedTool(parent=None, method=add)
        params = tool.get_parameters()
        names = [p.name for p in params]
        assert "a" in names and "b" in names
        assert tool.name == "add"

        resp = tool.run({"a": 3, "b": 5})
        assert resp.status == ToolStatus.SUCCESS
        assert resp.text == "8"
